"""Adiciona campo octopusasint

Revision ID: bd641431e2df
Revises: 79939df2376c
Create Date: 2025-08-14 01:05:55.995840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd641431e2df'
down_revision = '79939df2376c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pessoa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('octopusasint', sa.String(length=3), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pessoa', schema=None) as batch_op:
        batch_op.drop_column('octopusasint')

    # ### end Alembic commands ###
