"""reset migrations

Revision ID: c4888f9d838b
Revises: 
Create Date: 2025-12-29 17:29:11.154817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4888f9d838b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mandado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('genitora', sa.String(), nullable=True),
    sa.Column('tipificacao', sa.String(), nullable=True),
    sa.Column('data', sa.String(), nullable=True),
    sa.Column('endereco', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pessoa', schema=None) as batch_op:
        batch_op.drop_column('foto_backup')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pessoa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foto_backup', sa.TEXT(), autoincrement=False, nullable=True))

    op.drop_table('mandado')
    # ### end Alembic commands ###
